{
 "title": "Callysto Global",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Current Users Logged In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jupyterhub_running_servers)"
    }
   ]
  },
  {
   "title": "Total User Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_filesystem_device_error{mountpoint=~\"/tank/home/.+\"})"
    }
   ]
  },
  {
   "title": "Total User Count",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jupyterhub_running_servers) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total User Count",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sort_desc(count(node_filesystem_device_error{mountpoint=~\"/tank/home/.+\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lifetime user counts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(node_filesystem_device_error{mountpoint=~\"/tank/home/.+\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Running Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jupyterhub_running_servers) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{env=\"hub\",instance=~\"hub.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"hub.+\"} - node_memory_MemAvailable_bytes{instance=~\"hub.+\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"hub.+\", name=~\"jupyter-.+\"}) by(instance)",
     "legendFormat": "{{instance}} Container Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"hub.+\"}",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "ZFS Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_reads{instance=~\"hub.+\"}[5m])",
     "legendFormat": "{{instance}} zpool reads"
    },
    {
     "expr": "irate(node_zfs_zpool_writes{instance=~\"hub.+\"}[5m])",
     "legendFormat": "{{instance}} zpool writes"
    }
   ]
  },
  {
   "title": "ZFS Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_rtime{instance=~\"hub.+\"}[5m])",
     "legendFormat": "{{instance}} zpool rtime"
    },
    {
     "expr": "irate(node_zfs_zpool_wtime{instance=~\"hub.+\"}[5m])",
     "legendFormat": "{{instance}} zpool wtime"
    }
   ]
  },
  {
   "title": "ZFS ARC - Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{instance=~\"hub.+\"}",
     "legendFormat": "{{instance}} data"
    },
    {
     "expr": "node_zfs_arc_metadata_size{instance=~\"hub.+\"}",
     "legendFormat": "{{instance}}  metadata"
    },
    {
     "expr": "node_zfs_arc_anon_size{instance=~\"hub.+\"}",
     "legendFormat": "{{instance}}  anon"
    },
    {
     "expr": "node_zfs_arc_hdr_size{instance=~\"hub.+\"}",
     "legendFormat": "{{instance}}  hdr"
    },
    {
     "expr": "node_zfs_arc_other_size{instance=~\"hub.+\"}",
     "legendFormat": "{{instance}} other"
    }
   ]
  },
  {
   "title": "ZFS ARC - Hits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{instance=~\"hub.+\"}[5m]) / (irate(node_zfs_arc_demand_data_hits{instance=~\"hub.+\"}[5m]) + irate(node_zfs_arc_demand_data_misses{instance=~\"hub.+\"}[5m]))",
     "legendFormat": "{{instance}} hit ratio"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{instance=~\"hub.+\"}[5m])",
     "legendFormat": "{{instance}} hits"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses{instance=~\"hub.+\"}[5m])",
     "legendFormat": "{{instance}} misses"
    }
   ]
  }
 ]
}