- name: Add shibboleth repo
  template:
    src: "shibboleth.repo.j2"
    dest: "/etc/yum.repos.d/shibboleth.repo"
  become: yes

- name: Ensure shibboleth installed
  yum:
    name: shibboleth.x86_64
    state: present
    update_cache: yes
  become: yes

- name: Remove default conf files apache
  file:
    path: "{{ apache_conf_path }}/{{ item }}"
    state: absent
  with_items:
    - shib.conf
  notify:
    - reload httpd
  become: yes

- name: Copy default config files
  copy:
    src: 20_shib_apache24.conf
    dest: "{{ apache_conf_path }}/20_shib.conf"
  become: yes
  notify:
    - reload httpd

- name: Configure Shibboleth
  template:
    src: "shibboleth/{{ item }}.j2"
    dest: "/etc/shibboleth/{{ item }}"
  with_items:
    - attribute-map.xml
    - shibboleth2.xml
    - attribute-policy.xml
  become: yes
  notify:
    - restart shibd
    - reload httpd

- name: enable shibd
  service:
    name: "shibd"
    enabled: yes
  become: yes
  notify:
    - restart shibd
    - reload httpd
