---
## Configures the clavius virtual machine
- name: Ensure sudo is configured correctly
  hosts: clavius
  become: true
  tasks:
    # Settings are defined in
    # group_vars/all/sudo.yml
    # group_vars/infra/sudo.yml
    # host_vars/clavius/sudo.yml
    - name: Configure sudo
      tags: ["sudo", "always"]
      include_role:
        name: sudo
      vars:
          ansible_ssh_pipelining: no

- name: Manage Clavius
  hosts: clavius
  become: true
  tasks:
    - name: Ensure hostname is set
      tags: ["hostname"]
      include_role:
        name: hostname

    # Add relevant keys to `ssh_public_keys` defined in:
    # group_vars/all/local_vars.yml
    # group_vars/infra/local_vars.yml
    # host_vars/clavius/local_vars.yml
    - name: Manage SSH public keys
      tags: ["ssh"]
      include_role:
        name: ssh-public-keys

    # This also installs EPEL
    - name: Ensure base packages are installed
      tags: ["base-packages"]
      include_role:
        name: base-packages

    - name: Configure SELinux
      tags: ["selinux"]
      include_role:
        name: selinux
      vars:
        selinux_policy: targeted
        selinux_state: permissive

    # Enabled services are defined in
    # group_vars/all/firewalld.yml
    # group_vars/infra/firewalld.yml
    # host_vars/clavius/firewalld.yml
    - name: Ensure firewalld service is running
      tags: ["firewalld"]
      include_role:
        name: flatkey.firewalld

    - name: Manage Ansible
      tags: ["ansible"]
      include_role:
        name: ansible

    - name: Install kubectl
      tags: ["kubernetes"]
      include_role:
        name: kubernetes

    - name: Manage Docker
      include_role:
        name: docker

    - name: Manage Docker storage
      include_role:
        name: docker-storage

    - name: Ensure cryptsetup is installed
      yum:
        name: cryptsetup

    - name: Ensure dm_crypt module is loaded
      modprobe:
        name: dm_crypt

    - name: Ensure Python 3 is installed
      tags: ["python", "python3"]
      include_role:
        name: python38

    - name: Ensure OpenStack CLI tools are installed
      include_role:
        name: openstack-tools

    - name: Ensure mailx is installed
      yum:
        name: mailx

    - name: Ensure bind-utils is installed
      yum:
        name: bind-utils

    - name: Ensure docker python module is installed
      pip:
        name: docker

    - name: Install a newer version of Jinja2 for Ansible
      pip:
        name: jinja2
        version: 2.8
