---
# This is included by hub.yml
#
# This set of tasks will install and configure Docker on the hub.
# It installs docker-ce, configures the firewall appropriately,
# and ensures a defined block storage volume is used as /var/lib/docker.
#
- name: Manage Docker
  include_role:
    name: docker

- name: Add interfaces their respective zones
  firewalld:
    interface: '{{ item.interface }}'
    zone: '{{ item.zone }}'
    state: enabled
    permanent: true
    immediate: yes
  with_items:
    - { interface: '{{ docker_interface }}', zone: 'home' }
  notify:
    firewalld complete reload

- name: update facts if docker0 is not defined
  action: setup filter="ansible_docker0"
  when: ansible_docker0 is not defined

- name: Install docker module
  yum:
    name: 'python-docker-py'
    state: 'present'

- name: Manage Docker ephemeral storage
  include_role:
    name: docker-ephemeral
