---
## Runs basic tasks after infrastructure has been deployed via Terraform
- name: Initial tasks for Callysto Infrastructure
  hosts: all
  become: true
  vars:
        ansible_ssh_pipelining: no
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
      ignore_errors: true

    - name: Reboot instance
      command: needs-restarting -r
      register: command_restart
      failed_when: command_restart.rc not in [0, 1]
      check_mode: no
      changed_when: false

    - name: Reboot instance
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 30
        post_reboot_delay: 30
      when: command_restart.rc == 1
