---
# This is included by hub.yml
#
# This set of tasks will install and configure JupyterHub
# on the hub. The configuration is specific to Callysto.
#
- name: Manage Callysto html repo
  tags: ["httpd"]
  include_role:
    name: callysto-html

- name: Manage dockerspawner
  tags: ["jupyter", "docker", "python3"]
  include_role:
    name: dockerspawner

- name: Manage syzygyauthenticator
  tags: ["jupyter", "python3", "zfs", "ssp"]
  include_role:
    name: syzygyauthenticator

- name: Manage JupyterHub Docker Cull script
  tags: ["jupyter", "python3"]
  include_role:
    name: jhub-docker-cull

- name: Manage Jupyterhub
  tags: ["jupyter", "jupyterhub"]
  include_role:
    name: jupyterhub
