---
## Used by Packer to create a CentOS OpenStack image
## with all updates applied and core utilities installed.
- name: Initial tasks for Callysto Infrastructure
  hosts: all
  become: true
  tasks:
    - name: Install yum-plugin-versionlock
      yum:
        name: yum-plugin-versionlock
        state: latest
        update_cache: yes

    - name: Lock cloud-init due to IPv6 bug
      shell: yum versionlock cloud-init-*

    - name: Update all packages
      yum:
        name: "*"
        state: latest
      ignore_errors: true

    - name: Set net.ipv6.conf.default.accept_ra to 1 for IPv6
      sysctl:
        name: net.ipv6.conf.default.accept_ra
        value: 1

    - name: Set net.ipv6.conf.all.accept_ra.accept_ra to 1 for IPv6
      sysctl:
        name: net.ipv6.conf.all.accept_ra
        value: 1

    - name: Reboot instance
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true

    - name: wait for SSH access to come back
      wait_for_connection:
        delay: 65
        timeout: 300

- name: More initial tasks for Callysto Infrastructure
  hosts: all
  become: true
  tasks:
    - name: Configure sudo
      tags: ["sudo", "always"]
      include_role:
        name: sudo

    - name: Ensure base packages are installed
      tags: ["base-packages"]
      include_role:
        name: base-packages

    - name: Manage ZFS
      tags: ["zfs"]
      include_role:
        name: zfs
      vars:
        zfs_pool_name: tank

    - name: Configure SELinux
      tags: ["selinux"]
      include_role:
        name: selinux
      vars:
        selinux_policy: targeted
        selinux_state: permissive
