---
## Used by Packer to create an Ubuntu OpenStack image.
## with all updates applied and core utilities installed.
- name: Initial tasks for Callysto Infrastructure
  hosts: all
  become: true
  tasks:
    - name: Update all packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      ignore_errors: true

    - name: Reboot instance
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true

    - name: wait for SSH access to come back
      wait_for_connection:
        delay: 65
        timeout: 300

- name: More initial tasks for Callysto Infrastructure
  hosts: all
  become: true
  tasks:
    - name: Configure sudo
      tags: ["sudo", "always"]
      include_role:
        name: sudo

    - name: Ensure base packages are installed
      tags: ["base-packages"]
      include_role:
        name: base-packages

    - name: Manage ZFS
      tags: ["zfs"]
      include_role:
        name: zfs
      vars:
        zfs_pool_name: tank
