- name: restart shibd
  service:
    name: shibd
    state: restarted
  become: yes

- name: restart httpd
  service:
    name: httpd
    state: restarted
  become: yes

- name: reload httpd
  service:
    name: httpd
    state: reloaded
  become: yes
