---
- name: Install dockerspawner
  pip:
    name:
      - 'urllib3{{ dockerspawner_urllib3_version | default("latest") }}'
      - 'docker{{ dockerspawner_docker_version | default("") }}'
      - 'escapism{{ dockerspawner_escapism_version | default("") }}'
      - 'dockerspawner{{ dockerspawner_version | default("") }}'
    executable: '{{ python3_pip_executable }}'
