---
- name: Create application user
  user:
    name: "{{ edxapp_user }}"
    home: "{{ edxapp_app_dir }}"
    createhome: no
    shell: /bin/false

- name: Create jupyter user for jupyter notebooks
  user:
    name: jupyter
    home: /home/jupyter
    shell: /bin/bash
    groups: docker
    append: true

- name: Copy jupyter sudoers file
  copy:
    src: jupyter_sudo
    dest: /etc/sudoers.d/www-data-jupyter
    owner: root
    group: root
    mode: "0440"

- name: Copy updated requirements file for edx sandbox
  copy:
    src: edx-platform-base.txt
    dest: /tmp/edx-platform-base.txt
    owner: "{{ edxapp_user }}"
    group: "{{ edxapp_user }}"
    mode: "0644"
