---
- name: Create Diffie-Hellman parameters to prevent weak key exchange
  command: openssl dhparam -out /etc/ssl/private/dhparams.pem 2048
  args:
    chdir: /etc/ssl/private
    creates: /etc/ssl/private/dhparams.pem

- name: Manage nginx
  include_role:
    name: nginx

- name: Create default html directory
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: "0750"

- name: Manage rate-limit file
  copy:
    src: nginx/rate-limit.html
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: "0640"

- name: Manage server-error file
  copy:
    src: nginx/server-error.html
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: "0640"

- name: Manage main nginx config file
  copy:
    src: nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0640"
  notify: "(Handler: All OSs) Reload NGINX"

- name: Manage nginx site files
  copy:
    src: "nginx/{{ item }}.conf"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    owner: root
    group: root
    mode: "0640"
  with_items:
    - cms
    - lms
    - forum
    - discovery
    - maps
  notify: "(Handler: All OSs) Reload NGINX"
