- name: Install a remi php 8.2 module
  ansible.builtin.dnf:
    name: '@php:remi-8.2'
    state: present

- name: Ensure php packages installed
  yum:
    state: present
    update_cache: yes
    name:
      - php-cli
      - php-pdo
      - php-xml
      - php-soap
      - php-pecl-apcu
      - php-mbstring
      - php-gd
      - php-ldap
      - php-zip
  become: yes
  notify:
    - restart httpd
