- name: Copy composer installer
  template:
    src: get-composer.sh.j2
    dest: "{{ ssp_dir }}/get-composer.sh"
    mode: 0755
    owner: root
    group: root 

- name: Run composer installer (if needed)
  command: ./get-composer.sh
  args:
    chdir: "{{ ssp_dir }}/"
    creates: "{{ ssp_dir }}/composer.phar"

- name: Run composer authoauth2 installer
  command: "{{ php_executable }} composer.phar require cirrusidentity/simplesamlphp-module-authoauth2:{{ ssp_authoauth2_version }}"
  args:
    chdir: "{{ ssp_dir }}"
    creates: "{{ ssp_dir }}/modules/authoauth2/src/OAuth2ResponseHandler.php"

- name: Run composer authoauth2 installer
  command: "{{ php_executable }} composer.phar require simplesamlphp/simplesamlphp-module-smartattributes"
  args:
    chdir: "{{ ssp_dir }}"
    creates: "{{ ssp_dir }}/modules/smartattributes"
