---
# Manages an Open edX installation.
# This shouldn't be run on its own.
#
# NOTE: import_role is intentionally used in order for the
# tightly coupled edx roles to share variables.

- name: Validate edx configuration
  hosts: edx
  become: true
  tasks:
    - name: Ensure zfs_pool_name is set
      assert:
        that: >-
          zfs_pool_name is defined and zfs_pool_name != ""
        msg: "Must set zfs_pool_name. This is usually done automatically with Terraform"

    - name: Ensure zfs_disk_1 and zfs_disk_2 are set
      assert:
        that: >-
          zfs_disk_1 is defined and zfs_disk_1 != "" and zfs_disk_2 is defined and zfs_disk_2 != ""
        msg: "Must set zfs_disk_1 and zfs_disk_2. This is usually done automatically with Terraform"

    - name: Ensure callysto_ssl_cert_dir is set
      assert:
        that: >-
          callysto_ssl_cert_dir != ""
        msg: "Must set callysto_ssl_cert_dir"

    - name: Ensure either openstack_ephemeral_docker_disk or docker_zfs_pool is set
      assert:
        that: >-
          docker_zfs_pool is defined or
          (openstack_ephemeral_docker_disk is defined and
           openstack_ephemeral_docker_disk != "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_")
        msg: "Must set either openstack_ephemeral_docker_disk or docker_zfs_pool"

- name: Ensure sudo is configured correctly
  hosts: edx
  become: true
  tasks:
    # Settings are defined in
    # group_vars/<group>/sudo.yml
    - name: Configure sudo
      tags: ["sudo", "always"]
      include_role:
        name: sudo
      vars:
          ansible_ssh_pipelining: no

- name: Install and configure open edx
  hosts: edx
  become: true
  vars:
    docker_install_compose: true
    docker_compose_version: "1.25.1"
    zfs_containers:
      - tutor
  tasks:
    - name: Ensure hostname is set
      tags: ["init", "hostname"]
      include_role:
        name: hostname

    - name: Add /usr/local/bin/ to PATH
      copy:
        dest: /etc/profile.d/usrlocalbin.sh
        content: 'PATH=$PATH:/usr/local/bin'

    # Add relevant keys to `ssh_public_keys`
    # in either host_vars, group_vars, or local_vars.
    - name: Manage SSH public keys
      tags: ["init", "ssh"]
      include_role:
        name: ssh-public-keys

    # This also installs EPEL
    - name: Ensure base packages are installed
      tags: ["init", "base-packages"]
      include_role:
        name: base-packages

    # This will create and manage a zpool based on
    # `zfs_disk_1` and `zfs_disk_2` defined in local_vars.yml.
    - name: Manage ZFS
      tags: ["init", "zfs"]
      include_role:
        name: zfs

    # Configuration is stored in
    # group_vars/<group>/ssh.yml.
    - name: Ensure sshd is installed and running
      tags: ["init", "sshd"]
      include_role:
        name: sshd

    - name: Copy SSL certificates
      tags: ["init", "ssl"]
      include_role:
        name: callysto-ssl

    - name: Manage Python3
      tags: ["python", "python3"]
      include_role:
        name: ius-python3

    - name: Manage Docker
      include_role:
        name: docker

    - name: Manage Tutor
      include_role:
        name: callysto-edx
