---
# Manages a JupyterHub installation.
# This shouldn't be run on its own.
- name: Validate hub configuration
  hosts: hub
  become: true
  tasks:
    - name: Ensure zfs_pool_name is set
      assert:
        that: >-
          zfs_pool_name is defined and zfs_pool_name != ""
        msg: "Must set zfs_pool_name. This is usually done automatically with Terraform"

    - name: Ensure zfs_disk_1 and zfs_disk_2 are set
      assert:
        that: >-
          zfs_disk_1 is defined and zfs_disk_1 != "" and zfs_disk_2 is defined and zfs_disk_2 != ""
        msg: "Must set zfs_disk_1 and zfs_disk_2. This is usually done automatically with Terraform"

    - name: Ensure callysto_ssl_cert_dir is set
      assert:
        that: >-
          callysto_ssl_cert_dir != ""
        msg: "Must set callysto_ssl_cert_dir"

    - name: Ensure either openstack_ephemeral_docker_disk or docker_zfs_pool is set
      assert:
        that: >-
          docker_zfs_pool is defined or
          (openstack_ephemeral_docker_disk is defined and
           openstack_ephemeral_docker_disk != "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_")
        msg: "Must set either openstack_ephemeral_docker_disk or docker_zfs_pool"

    - name: Ensure either openstack credentials are supplied with syzygyswiftspawner
      assert:
        that: >-
          jupyterhub_spawner != 'syzygyswiftspawner' or
          (jupyterhub_spawner == 'syzygyswiftspawner' and openstack_auth_url is defined)
        msg: "Must supply openstack credentials when using syzygyswiftspawner"

    - name: Ensure callysto-swift is used when syzygyswiftspawner is used
      assert:
        that: >-
          jupyterhub_spawner != 'syzygyswiftspawner' or
          (jupyterhub_spawner == 'syzygyswiftspawner' and jupyterhub_docker_image == 'docker.io/callysto/callysto-swift')
        msg: "Must use callysto-swift image with syzygyswiftspawner"

    - name: Ensure callysto-swift is not used when syzygyswiftspawner not is used
      assert:
        that: >-
          (jupyterhub_spawner == 'syzygyswiftspawner' and jupyterhub_docker_image == 'docker.io/callysto/callysto-swift') or
          jupyterhub_docker_image != 'docker.io/callysto/callysto-swift'
        msg: "Can only use callysto-swift image with syzygyswiftspawner"

    - name: Ensure ssp_multi_salt is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_idp_multi_salt is defined and ssp_idp_multi_salt != '')
        msg: "Must set ssp_idp_multi_salt when using shib authenticator"

    - name: Ensure ssp_idp_multi_admin_password is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_idp_multi_admin_password is defined and ssp_idp_multi_admin_password != '')
        msg: "Must set ssp_idp_multi_admin_password when using shib authenticator"

    - name: Ensure ssp_refresh_key is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_refresh_key is defined and ssp_refresh_key != '')
        msg: "Must set ssp_refresh_key when using shib authenticator"

    - name: Ensure ssp_idp_multi_saml_cert is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_idp_multi_saml_cert is defined and ssp_idp_multi_saml_cert != '')
        msg: "Must set ssp_idp_multi_saml_cert when using shib authenticator"

    - name: Ensure ssp_idp_multi_saml_key is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_idp_multi_saml_key is defined and ssp_idp_multi_saml_key != '')
        msg: "Must set ssp_idp_multi_saml_key when using shib authenticator"

    - name: Ensure ssp_domain is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_domain is defined and ssp_domain != '')
        msg: "Must set ssp_domain when using shib authenticator"

    - name: Ensure hub_metrics is set
      assert:
        that: >-
          hub_metrics is defined
        msg: "Must set hub_metrics to true or false"

- name: Generic Callysto host configuration
  hosts: hub
  become: true
  tasks:
    - name: Ensure hostname is set
      tags: ["hostname"]
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'

    # Add relevant keys to `ssh_public_keys`
    # in either host_vars, group_vars, or local_vars.
    - name: Manage SSH public keys
      tags: ["ssh"]
      ansible.posix.authorized_key:
        user: '{{ item.value.user }}'
        state: '{{ item.value.state }}'
        key: '{{ item.value.public_key }}'
      with_dict: '{{ ssh_public_keys }}'
      when: ssh_public_keys is defined

    - name: Install Base Packages
      become: true
      tags: ["base-packages"]
      ansible.builtin.yum:
        name: '{{ item }}'
        state: present
      with_items: '{{ base_packages }}'
      when: base_packages is defined

    - name: Configure SELinux
      tags: ["selinux"]
      ansible.posix.selinux:
        policy: targeted
        state: permissive

    - name: Ensure firewalld service is running
      become: true
      tags:
        - firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Poke firewall holes
      become: true
      tags:
        - firewalld
      ansible.posix.firewalld:
        service: '{{ item.value.service }}'
        permanent: "{{ item.value.permanent | default('yes') }}"
        state: '{{ item.value.state }}'
        zone: '{{ item.value.zone }}'
      with_dict: '{{ firewalld_service_rules }}'
      when: firewalld_service_rules is defined

    - name: Install Python Environment
      become: true
      tags:
        - python
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items:
        - python3.11
        - python3.11-pip
        - python3.11-devel

    - name: Set Python3.11 as the default
      become: true
      tags:
        - python
      community.general.alternatives:
        name: python3
        path: /usr/bin/python3.11
        link: /usr/bin/python3

    - name: Set pip3.11 as the default
      become: true
      tags:
        - python
      community.general.alternatives:
        name: pip3
        path: /usr/bin/pip3.11
        link: /usr/bin/pip3

    - name: Update Needs-Restarting python
      become: true
      tags:
        - python
      lineinfile:
        dest: /usr/bin/needs-restarting
        regexp: '^#!/usr/bin/python3$'
        line: '#!/usr/bin/python3.9'



- name: Install and configure the hub
  hosts: hub
  become: true
  roles:
    - { role: geerlingguy.repo-epel, become: yes}
    - { role: weareinteractive.sudo, become: yes }
    - { role: devsec.hardening.ssh_hardening, become: yes }

    - role: sysstat
      become: yes

    - role: geerlingguy.apache
      become: yes

    # This will create and manage a zpool based on
    # `zfs_disk_1` and `zfs_disk_2` defined in local_vars.yml.
    - name: Manage ZFS
      tags: ["zfs"]
      role: zfs

    - name: Copy SSL certificates
      role: callysto-ssl

    # Manage Docker
    - name: Manage Docker
      role: geerlingguy.docker
      become: yes
      tags: ["docker"]

    - role: docker-extra
      become: yes
      tags:
        - docker

    - role: geerlingguy.nodejs
      become: yes
      tags:
        - nodejs
        - npm

    - name: Manage Callysto html repo
      role: callysto-html

    - name: Manage Jupyterhub
      tags: ["jupyter", "jupyterhub", "ssp"]
      role: jupyterhub

    - name: Manage Shibboleth
      tags: ["shib"]
      role: shibboleth
      when: jupyterhub_authenticator == 'shib'

    # Only manage ssp in all-in-one configurations
    - name: Manage SimpleSAMLphp
      tags: ["ssp"]
      role: ssp-idp-multi
      when: groups['ssp'][0] == groups['hub'][0] and jupyterhub_authenticator == 'shib'

    - name: Manage rrsync script
      tags: ["ssh", "rrsync", "backup"]
      role: rrsync

    - name: Manage openstack tools and openrc file
      tags: ["openstack"]
      role: openstack-tools
