---
# Manages a JuptyerHub installation.
# This shouldn't be run on its own.
- name: Validate hub configuration
  hosts: hub
  become: true
  tasks:
    - name: Ensure zfs_pool_name is set
      assert:
        that: >-
          zfs_pool_name is defined and zfs_pool_name != ""
        msg: "Must set zfs_pool_name. This is usually done automatically with Terraform"

    - name: Ensure zfs_disk_1 and zfs_disk_2 are set
      assert:
        that: >-
          zfs_disk_1 is defined and zfs_disk_1 != "" and zfs_disk_2 is defined and zfs_disk_2 != ""
        msg: "Must set zfs_disk_1 and zfs_disk_2. This is usually done automatically with Terraform"

    - name: Ensure callysto_ssl_cert_dir is set
      assert:
        that: >-
          callysto_ssl_cert_dir != ""
        msg: "Must set callysto_ssl_cert_dir"

    - name: Ensure either openstack_ephemeral_docker_disk or docker_zfs_pool is set
      assert:
        that: >-
          docker_zfs_pool is defined or
          (openstack_ephemeral_docker_disk is defined and
           openstack_ephemeral_docker_disk != "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_")
        msg: "Must set either openstack_ephemeral_docker_disk or docker_zfs_pool"

    - name: Ensure either openstack credentials are supplied with syzygyswiftspawner
      assert:
        that: >-
          jupyterhub_spawner != 'syzygyswiftspawner' or
          (jupyterhub_spawner == 'syzygyswiftspawner' and openstack_auth_url is defined)
        msg: "Must supply openstack credentials when using syzygyswiftspawner"

    - name: Ensure callysto-swift is used when syzygyswiftspawner is used
      assert:
        that: >-
          jupyterhub_spawner != 'syzygyswiftspawner' or
          (jupyterhub_spawner == 'syzygyswiftspawner' and jupyterhub_docker_image == 'docker.io/callysto/callysto-swift')
        msg: "Must use callysto-swift image with syzygyswiftspawner"

    - name: Ensure callysto-swift is not used when syzygyswiftspawner not is used
      assert:
        that: >-
          (jupyterhub_spawner == 'syzygyswiftspawner' and jupyterhub_docker_image == 'docker.io/callysto/callysto-swift') or
          jupyterhub_docker_image != 'docker.io/callysto/callysto-swift'
        msg: "Can only use callysto-swift image with syzygyswiftspawner"

    - name: Ensure ssp_multi_salt is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_idp_multi_salt is defined and ssp_idp_multi_salt != '')
        msg: "Must set ssp_idp_multi_salt when using shib authenticator"

    - name: Ensure ssp_idp_multi_admin_password is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_idp_multi_admin_password is defined and ssp_idp_multi_admin_password != '')
        msg: "Must set ssp_idp_multi_admin_password when using shib authenticator"

    - name: Ensure ssp_refresh_key is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_refresh_key is defined and ssp_refresh_key != '')
        msg: "Must set ssp_refresh_key when using shib authenticator"

    - name: Ensure ssp_idp_multi_saml_cert is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_idp_multi_saml_cert is defined and ssp_idp_multi_saml_cert != '')
        msg: "Must set ssp_idp_multi_saml_cert when using shib authenticator"

    - name: Ensure ssp_idp_multi_saml_key is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_idp_multi_saml_key is defined and ssp_idp_multi_saml_key != '')
        msg: "Must set ssp_idp_multi_saml_key when using shib authenticator"

    - name: Ensure hub_domain is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (hub_domain is defined and hub_domain != '')
        msg: "Must set hub_domain when using shib authenticator"

    - name: Ensure ssp_domain is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_domain is defined and ssp_domain != '')
        msg: "Must set ssp_domain when using shib authenticator"

    - name: Ensure hub_metrics is set
      assert:
        that: >-
          hub_metrics is defined
        msg: "Must set hub_metrics to true or false"

- name: Ensure sudo is configured correctly
  hosts: hub
  become: true
  tasks:
    # Settings are defined in
    # group_vars/<group>/sudo.yml
    - name: Configure sudo
      tags: ["sudo", "always"]
      include_role:
        name: sudo
      vars:
          ansible_ssh_pipelining: no

- name: Install and configure the hub
  hosts: hub
  become: true
  tasks:
    - name: Ensure hostname is set
      tags: ["hostname"]
      include_role:
        name: hostname

    # Add relevant keys to `ssh_public_keys`
    # in either host_vars, group_vars, or local_vars.
    - name: Manage SSH public keys
      tags: ["ssh"]
      include_role:
        name: ssh-public-keys

    # This also installs EPEL
    - name: Ensure base packages are installed
      tags: ["base-packages"]
      include_role:
        name: base-packages

    # This will create and manage a zpool based on
    # `zfs_disk_1` and `zfs_disk_2` defined in local_vars.yml.
    - name: Manage ZFS
      tags: ["zfs"]
      include_role:
        name: zfs

    - name: Configure SELinux
      tags: ["selinux"]
      include_role:
        name: selinux
      vars:
        selinux_policy: targeted
        selinux_state: permissive

    # Enabled services are defined in
    # group_vars/hub/firewalld.yml
    #
    # The jupyterhub role also enables access
    # to `jupyterhub_api_port`.
    - name: Ensure firewalld service is running
      tags: ["firewalld"]
      include_role:
        name: firewalld

    # Configuration is stored in
    # group_vars/<group>/ssh.yml.
    - name: Ensure sshd is installed and running
      tags: ["sshd"]
      include_role:
        name: sshd

    - name: Copy SSL certificates
      include_role:
        name: callysto-ssl

    # Configuration is stored in
    # group_vars/<group>/httpd.yml
    - name: Manage Apache
      tags: ["httpd"]
      include_role:
        name: apache

    - name: Manage Python3
      tags: ["python", "python3"]
      include_role:
        name: ius-python3

    # Manage Docker
    - name: Manage Docker
      include_role:
        name: docker

    - name: Add interfaces their respective zones
      firewalld:
        interface: '{{ item.interface }}'
        zone: '{{ item.zone }}'
        state: enabled
        permanent: true
        immediate: yes
      with_items:
        - { interface: '{{ docker_interface }}', zone: 'home' }
        - { interface: 'eth0', zone: 'public' }
      notify:
        firewalld complete reload

    - name: update facts if docker0 is not defined
      action: setup filter="ansible_docker0"
      when: ansible_docker0 is not defined

    - name: Install docker module
      yum:
        name: 'python-docker-py'
        state: 'present'

    - name: Manage Docker storage
      include_role:
        name: docker-storage

    - name: Manage Callysto html repo
      include_role:
        name: callysto-html

    - name: Manage Jupyterhub
      tags: ["jupyter", "jupyterhub", "ssp"]
      include_role:
        name: jupyterhub

    - name: Manage Shibboleth
      tags: ["shib"]
      include_role:
        name: shibboleth
      when: jupyterhub_authenticator == 'shib'

    # Only manage ssp in all-in-one configurations
    - name: Manage SimpleSAMLphp
      tags: ["ssp"]
      include_role:
        name: ssp-idp-multi
      when: groups['ssp'][0] == groups['hub'][0] and jupyterhub_authenticator == 'shib'

    - name: Manage rrsync script
      tags: ["ssh", "rrsync", "backup"]
      include_role:
        name: rrsync

    - name: Prometheus node-exporter
      tags: ["stats","prometheus"]
      include_role:
        name: prometheus-node-exporter
      vars:
        prometheus_node_exporter_config_flags:
           'web.listen-address': '127.0.0.1:9100'
           'log.level': 'info'
      when: hub_metrics
