---
# Manages stats configuration on SimpleSAMLphp
# This shouldn't be run on its own.
- name: Manage stats components on JupyterHub
  hosts: ssp
  become: true
  vars:
    caddy_port: 9999
    caddy_port_mappings:
      node: 9100
  tasks:
    - name: Manage Caddy
      tags: ["stats", "caddy"]
      include_role:
        name: caddy
      vars:
        caddy_user: "root"
        caddy_home: "/root"
        caddy_config: |
          :{{ caddy_port }}
          tls /etc/pki/tls/certs/fullchain.pem /etc/pki/tls/private/privkey.pem
          {% for name, port in caddy_port_mappings.items() %}
          basicauth /{{ name }} {{ stats_username }} {{ stats_password }}
          proxy /{{ name }} 127.0.0.1:{{ port }} {
            without /{{ name }}
          }
          {% endfor %}

    - name: Prometheus node exporter
      tags: ["stats", "node-exporter"]
      include_role:
        name: prometheus-node-exporter
      vars:
        prometheus_node_exporter_config_flags:
           'web.listen-address': '127.0.0.1:9100'
           'log.level': 'info'
