zfs_pool_name: tank

zfs_create_pool: true

zfs_module_dkms: false

zfs_repo_url: https://zfsonlinux.org/epel/zfs-release-2-3.el{{ ansible_distribution_major_version }}.noarch.rpm

zfs_repo_gpg_key_url: https://raw.githubusercontent.com/zfsonlinux/zfsonlinux.github.com/master/zfs-release/RPM-GPG-KEY-openzfs-key2

#
# A string containing a valid zfs vdev specification
# e.g. 
#  zfs_vdev_config: mirror /dev/sda /dev/sdb
#  zfs_vdev_config: /dev/sdb
#  zfs_vdev_config: raidz /dev/sda /dev/sdb /dev/sdb
#  
# This variable is intentionally left blank because the zpool create process
# will destroy any existing data on the devices specified
