---
- name: Install sysstat
  ansible.builtin.package:
    name: "{{ sysstat_packages }}"
    state: present

- name: Start and enable sysstat
  ansible.builtin.service:
    name: "{{ sysstat_service }}"
    state: started
    enabled: true
  when:
    - sysstat_service | length
