---
roles:
  - name: geerlingguy.repo-epel
    version: 3.1.1
  - name: geerlingguy.repo-remi
    version: 2.1.0
  - name: geerlingguy.docker
    version: 7.3.0
  - name: geerlingguy.ansible
    version: 2.3.0
  - name: geerlingguy.apache
    version: 4.0.0
  - name: geerlingguy.nodejs
    version: 7.0.0
  - name: willshersystems.sshd
    version: v0.24.1
  - name: weareinteractive.sudo
    version: 1.14.1

collections:
  - name: ansible.posix
    version: 1.5.4
    source: https://galaxy.ansible.com
  - name: community.general
    version: 9.2.0
    source: https://galaxy.ansible.com
  - name: devsec.hardening
    version: 9.0.1
    source: https://galaxy.ansible.com
  - name: prometheus.prometheus
    version: 0.17.0
    source: https://galaxy.ansible.com
  - name: grafana.grafana
    version: 5.4.0
