---
- name: deamon reload
  command: systemctl daemon-reload

- name: Restart JupyterHub
  service:
    name: jupyterhub
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted
  become: yes
