---
- name: Install zfs-release
  yum:
    name: '{{ zfs_release_rpm }}'
    state: present
  register: zfs_repo
  notify:
    - Remove existing zfs packages
  when: zfs_pool_name != ""

- name: Flush ZFS Handlers
  meta: flush_handlers

- name: Clean yum if zfs repo pkg installed
  command: yum clean all
  when: zfs_repo.changed and zfs_pool_name != ""

- name: Install zfs kernel module
  yum:
    name: zfs
    state: present
    update_cache: yes
  notify:
    - Modprobe zfs
  when: zfs_pool_name != ""

- name: Load the module at boot
  copy:
    src: zfs.conf
    dest: /etc/modules-load.d/zfs.conf
    owner: root
    group: root
    mode: 0640
